- name: setup build environment for xrootd
  hosts: localhost
  vars:
    xrootd_repo_url: "https://github.com/alex-rg/xrootd"
    xrdceph_repo_url: "https://github.com/stfc/xrootd-ceph"
    xrootd_branch: "version_533_with_dh_fix"
    xrdceph_branch: "bufferedIO"
    xrootd_version: "v5.3.3-15"
    xrdceph_version: "v5.3.3-15"
    build_dir: /root/build
    src_dir: /root/src
    xrootd_src_dir: "{{src_dir}}/xrootd"
    xrdceph_src_dir: "{{src_dir}}/xrdceph"
    xrootd_build_dir: "{{build_dir}}/xrootd"
    xrdceph_build_dir: "{{build_dir}}/xrdceph"
  tasks:
  - name: create repo dir
    file:
      path: "{{item}}"
      state: directory
    loop: ["{{xrootd_build_dir}}", "{{xrdceph_build_dir}}", "{{xrootd_src_dir}}", "{{xrdceph_src_dir}}"]

  - name: install ceph repo
    copy:
      content: |
        [ceph-el7-x86_64]
        name = ceph-el7-x86_64
        baseurl = http://mirrors.gridpp.rl.ac.uk/current/ceph-el7-x86_64/RPMS.nautilus/
        metadata_expire = 7d
        enabled = 1
        gpgcheck = 0
        priority = 40
        skip_if_unavailable = 0
      dest: /etc/yum.repos.d/ceph.repo
      owner: root
      group: root
      mode: 0644

  - name: install build packages
    yum:
      name: "{{item}}"
      state: present
    loop:
    - cmake3
    - git
    - centos-release-scl
    - devtoolset-7
    - librados2-devel
    - libradospp-devel
    - libradosstriper-devel
    - krb5-devel
    - readline-devel
    - fuse-devel
    - libxml2-devel
    - zlib-devel
    - ncurses-devel
    - libcurl-devel
    - libuuid-devel
    - voms-devel
    - libmacaroons-devel
    - json-c-devel
    - python2-devel
    - python3-devel
    - openssl-devel
    - selinux-policy-devel
    - doxygen
    - graphviz
    - systemd-devel
    - rpm-build
    - scitokens-cpp-devel

  - name: clone Xrootd repository
    command:
      cmd: git clone -b "{{xrootd_branch}}" "{{xrootd_repo_url}}"
      chdir: "{{xrootd_src_dir}}"

  - name: create srpm
    command:
      cmd: "./makesrpm.sh --version 5.5.4-00 --define '_with_python3 1' --define '_with_tests 1' --define '_with_scitokens 1' --output {{xrootd_build_dir}}"
      chdir: "{{xrootd_src_dir}}/xrootd/packaging"

  - name: create output dir
    file:
      path: "{{item}}/RPMS"
      state: directory
    loop: ["{{xrootd_build_dir}}", "{{xrdceph_build_dir}}"]

  - name: build rpm
    shell:
      cmd: rpmbuild --rebuild --define "_rpmdir RPMS/" --define "_with_python3 1" --define "_with_scitokens 1"  --define "_build_name_fmt %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm" -D "dist .el7"  *.src.rpm
      chdir: "{{xrootd_build_dir}}"
